#version 450
// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 RafaelNGP
// FSR 1 EASU: the picture (any size) upscaled to the display's.
#extension GL_GOOGLE_include_directive : require
layout(local_size_x = 8, local_size_y = 8) in;
layout(binding = 0) uniform sampler2D inputTex;  // linear
layout(binding = 1, rgba8) uniform writeonly image2D upscaled;
layout(push_constant) uniform Constants {
    uvec4 con0, con1, con2, con3;
} pc;

#define A_GPU 1
#define A_GLSL 1
#include "ffx_a.h"
#define FSR_EASU_F 1
AF4 FsrEasuRF(AF2 p) { return textureGather(inputTex, p, 0); }
AF4 FsrEasuGF(AF2 p) { return textureGather(inputTex, p, 1); }
AF4 FsrEasuBF(AF2 p) { return textureGather(inputTex, p, 2); }
#include "ffx_fsr1.h"

void main() {
    uvec2 p = gl_GlobalInvocationID.xy;
    ivec2 size = imageSize(upscaled);
    if (p.x >= uint(size.x) || p.y >= uint(size.y)) return;
    vec3 color;
    FsrEasuF(color, p, pc.con0, pc.con1, pc.con2, pc.con3);
    imageStore(upscaled, ivec2(p), vec4(color, 1.0));
}
